routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::namespace('Frontend')->name('frontend.')->group(function () {

     // Route::get('/', 'FrontendController@index')->name('home1');
     // Route::get('/hotshot-originals', 'FrontendController@originalsListing')->name('hotshot-originals');
     // Route::get('/hotshot-x', 'FrontendController@XListing')->name('hotshot-x');
     // Route::get('/hotshot-videos', 'FrontendController@videosListing')->name('hotshot-videos');
     // Route::get('/movie/{slug}', 'FrontendController@movie')->name('movie');
     // Route::get('/gallery', 'FrontendController@gallery')->name('gallery');
     // Route::post('/gallery-form-submit', 'FrontendController@galleryPost')->name('gallery-form-submit');
     // Route::view('/terms-of-use', 'frontend.pages.terms')->name('terms-of-use');
     // Route::view('/privacy-policy', 'frontend.pages.policy')->name('privacy-policy');
     // Route::view('/contest-rules', 'frontend.pages.contest-rules')->name('contest-rules');
});

/*
|--------------------------------------------------------------------------
| Register the typical authentication routes for an application.
| Replacing: Auth::routes();
|--------------------------------------------------------------------------
*/

Route::namespace('Auth')->prefix(config('constants.backend_url_prefix'))->group(function () {
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->post('logout', 'LoginController@logout')->name('logout');
    // Registration Routes...
    if (config('constants.register')) {
        $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
        $this->post('register', 'RegisterController@register');
    }
    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
*/

Route::namespace('Backend')->prefix(config('constants.backend_url_prefix'))->name('backend.')->middleware(['auth'])->group(function () {

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::resource('users', 'UserController');
    Route::resource('team', 'TeamController');
    Route::resource('movie', 'MovieController');
    Route::resource('cast', 'CastController');
    Route::resource('video', 'HotVideosController');
    Route::resource('banners', 'BannersController');
    Route::resource('gallery-form', 'GalleryController');
    Route::resource('employee', 'EmployeeController');

    Route::get('movie/deletepic/{id}','MovieController@deletepic');

    Route::post('/movie-gallery-delete/{id}', 'MovieController@deleteGalleryImage')->name('movie-gallery-delete');

    Route::post('/movie-gallery-update/{id}', 'MovieController@updateGalleryImage')->name('movie-gallery-update');

    Route::post('/movie-bts-delete/{id}', 'MovieController@deleteBTSImage')->name('movie-bts-delete');

    Route::post('/movie-bts-update/{id}', 'MovieController@updateBTSImage')->name('movie-bts-update');
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employee';
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
public function __construct()
{
}
public function redirectToIndex($indexPage, $message = '')
{
return redirect()->route("backend.{$indexPage}.index")->with([
'message' => $message
]);
}

public function responseToJson($message = '')
{
return response()->json([
'message' => $message
]);
}
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

class DashboardController extends BackendController
{
    public function index()
    {
        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/EmployeeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Employee;
use App\Models\Movie_gallery_image;
use Config;

class EmployeeController extends BackendController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = new Employee();
        $datas=$data->all();
        return view('backend.employee.index',compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $datas = Employee::all();
        return view('backend.employee.create')->with(['datas' => $datas]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->mcast);
       // $request->validate([
       //      'front_name' => 'required|max:255',
       //      'description' => 'required',
       //      'position' => 'required',
       //  ]);

        // dd($request->all());

        $feature_image = null;
        if ($request->hasFile('feature_image')) {
                $file = $request->file('feature_image');
                $filename = $file->getClientOriginalName();
                $feature_image = date('His').$filename;
                $destinationPath = Config::get('constants.image_dir');
                $file->move($destinationPath, $feature_image);
        }

        $movie = new Employee();
        $movie->photo = $feature_image;
        $movie->name = $request->employee_name;
        $movie->mobile = $request->full_phone;
        $movie->email = $request->email_id;
        $movie->birth = $request->birth;
        $movie->unique_id = $request->employee_id;
        $movie->save();

        return $this->redirectToIndex('employee', config('constants.message.save'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Employee::findOrFail($id);

        return view("backend.employee.edit",compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $movie = Employee::Findorfail($id);

        if ($request->hasFile('feature_image')) {
                $file = $request->file('feature_image');
                $filename = $file->getClientOriginalName();
                $feature_image = date('His').$filename;
                $destinationPath = Config::get('constants.image_dir');
                $file->move($destinationPath, $feature_image);

                 $movie->photo = $feature_image;
        }
        $movie->name = $request->employee_name;
        $movie->mobile = $request->full_phone;
        $movie->email = $request->email_id;
        $movie->birth = $request->birth;
        $movie->unique_id = $request->employee_id;
        $movie->save();

         return $this->redirectToIndex('employee', config('constants.message.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $movie=Employee::Findorfail($id);
       $movie->delete();
       // return $this->responseToJson(config('constants.message.delete'));
       return $this->redirectToIndex('employee', config('constants.message.delete'));
    }



}

resources/views/backend/employee/create.blade.php
@extends('layouts.app')

@section('contentheader_title')
    EMPLOYEE
@endsection


 @section('content')
        <form action="{{ route('backend.employee.store')}}" method="post" enctype="multipart/form-data" id="form-data">
          @csrf

            <div class="form-group" style="position: relative;overflow: hidden;">
                <label for="feature_image">Employee Image</label>
               <input id="feature_image" type="file" name="feature_image">
            </div>

             <div class="form-group">
               <label for="name">Employee Name</label>
               <input type="text" name="employee_name" id="employee_name" class="form-control" value="" required="required">
             </div>

             <div class="form-group">
              <label for="front_year">Employee ID</label>
              <input type="text" name="employee_id" id="employee_id" class="form-control" minlength="5" maxlength="5" value="" required="required">
             </div>

            <div class="form-group">
                <label for="front_year">Date of Birth</label>
                <input type="text" name="birth" id="birth" class="form-control" value="" readonly="readonly">
            </div>

              <div class="form-group">
                <label for="description">Email ID</label>
                <input type="email" name="email_id" id="email_id" class="form-control" value="" required="required">
              </div>

              <div class="form-group">
              <label for="release_date">Mobile</label>
              <input type="text" name="mobile" id="mobile" class="form-control" value="" minlength="10" maxlength="10">
              <span id="valid-msg" class="hide">✓ Valid</span>
              <span id="error-msg" class="hide"></span>
             </div>

            <h5 class="text-right">
              <button class="btn btn-primary btn-md">SAVE</button>
              <button type="reset" class="btn btn-primary btn-md">CANCEL</button>
            </h5>
        </form>
@endsection

@push('scripts')
    <script>
tinymce.init({
selector: '.dynamic-editor'
});

$("#mobile").intlTelInput({
    nationalMode: true,
    // initialCountry: "India",
});

var input = document.querySelector("#mobile"),
  errorMsg = document.querySelector("#error-msg"),
  validMsg = document.querySelector("#valid-msg");

// here, the index maps to the error code returned from getValidationError - see readme
var errorMap = ["Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];

// initialise plugin
var iti = window.intlTelInput(input, {
  utilsScript: "{{ asset('tel/js/utils.js') }}"
});

var reset = function() {
  input.classList.remove("error");
  errorMsg.innerHTML = "";
  errorMsg.classList.add("hide");
  validMsg.classList.add("hide");
};

// on blur: validate
input.addEventListener('blur', function() {
  reset();
  if (input.value.trim()) {
    if (iti.isValidNumber()) {
      validMsg.classList.remove("hide");
      return true;
    } else {
      input.classList.add("error");
      var errorCode = iti.getValidationError();
      errorMsg.innerHTML = errorMap[errorCode];
      errorMsg.classList.remove("hide");
      return false;
    }
  }
});

// on keyup / change flag: reset
input.addEventListener('change', reset);
input.addEventListener('keyup', reset);


var input = document.querySelector("#mobile");
window.intlTelInput(input, {
  hiddenInput: "full_phone",
  utilsScript: "{{ asset('tel/js/utils.js') }}" // just for formatting/placeholders etc
});

$('#birth').datepicker({
    format: 'dd-mm-yyyy',
});

jQuery.validator.addMethod("lettersonly", function(value, element) {
  return this.optional(element) || /^[a-z]+$/i.test(value);
}, "Letters only please"); 

$('#form-data').validate({
    errorElement: "span",
    rules: {
        employee_name: {
          required: true,
          lettersonly: true,
        },
        email_id: {
            required: true,
            email: true,
        },
        feature_image: {
            extension: "jpg|png|jpeg",
        },
        employee_id: {
            required: true,
            minlength: 5,
            maxlength: 5,
        },
        mobile: {
            minlength: 10,
            maxlength: 10,
        },
    },
    messages: {
      required: "This field is required",
      lettersonly: "Only alphabetic characters is valid",
      email: "Please enter a valid email address",
      extension: "Your image must be in valid format",
    },
    submitHandler: function(form) {
    // do other things for a valid form
    form.submit();
    }
});

function deleteGalleryByUrl(url, type, elem) {
    var req_data = {_token: $('meta[name="csrf-token"]').attr('content')};
    $.ajax({
        url: url,
        type: type,
        data: req_data,
        success: function (response) {
            $(elem).parents(".img-rem").remove();
        }
    });
}


function updateGalleryByUrl(url, type, elem) {
    var img_data = $(elem).parents('.position').find('input[name="img-position"]').val();
    var req_data = {'img_position': img_data, _token: $('meta[name="csrf-token"]').attr('content')};
    console.log(req_data);
    $.ajax({
        url: url,
        type: type,
        data: req_data,
        success: function (response) {
            alert('Position Updated');
//                                            $(elem).parents(".img-rem").remove();
            // swal(response);
            swal("Poof! Your imaginary file has been updated!", {
                title: "Position Updated",
                icon: "success"
            });
        }
    });
}


function deleteBTSByUrl(url, type, elem) {
    var req_data = {_token: $('meta[name="csrf-token"]').attr('content')};
    $.ajax({
        url: url,
        type: type,
        data: req_data,
        success: function (response) {
            $(elem).parents(".img-rem").remove();
        }
    });
}


function updateBTSByUrl(url, type, elem) {
    var img_data = $(elem).parents('.position').find('input[name="img-position"]').val();
    var req_data = {'img_position': img_data, _token: $('meta[name="csrf-token"]').attr('content')};
    console.log(req_data);
    $.ajax({
        url: url,
        type: type,
        data: req_data,
        success: function (response) {
            alert('Position Updated');
//                                            $(elem).parents(".img-rem").remove();
            // swal(response);
            swal("Poof! Your imaginary file has been updated!", {
                title: "Position Updated",
                icon: "success"
            });
        }
    });
}

</script>
@endpush

resources/views/backend/employee/edit.blade.php
@extends('layouts.app')

@section('contentheader_title')
    EMPLOYEE
@endsection
@section('head-extras')

@endsection
  @section('content')
        <form action="{{ route('backend.employee.update',['id'=>$data->id]) }}" method="post"  enctype="multipart/form-data">
        <input type="hidden" name="_method" value="PUT">
        @csrf

            <div class="form-group" style="position: relative;overflow: hidden;">
            <label for="image">Employee Image</label><br>
            <img src="{{asset(Config::get('constants.image_dir').'/'.$data->photo)}}" height='100' width="100" style="border: 1px dotted #000000;">
            <input id="feature_image" type="file" name="feature_image">
            </div>

             <div class="form-group">
               <label for="name">Employee Name</label>
               <input type="text" name="employee_name" id="employee_name" class="form-control" value="{{ $data->name }}" required="required">
             </div>

             <div class="form-group">
              <label for="front_year">Employee ID</label>
              <input type="text" name="employee_id" id="employee_id" class="form-control" minlength="5" maxlength="5" value="{{ $data->unique_id }}" required="required">
             </div>

            <div class="form-group">
                <label for="front_year">Date of Birth</label>
                <input type="text" name="birth" id="birth" class="form-control" value="{{ $data->birth }}" readonly="readonly">
            </div>

              <div class="form-group">
                <label for="description">Email ID</label>
                <input type="email" name="email_id" id="email_id" class="form-control" value="{{ $data->email }}" required="required">
              </div>

              <div class="form-group">
              <label for="release_date">Mobile</label>
              <input type="text" name="mobile" id="mobile" class="form-control" value="{{ $data->mobile }}">
              <span id="valid-msg" class="hide">✓ Valid</span>
              <span id="error-msg" class="hide"></span>
             </div>

            <h5 class="text-right">
              <button class="btn btn-primary btn-md">SAVE</button>
            </h5>
        </form>
  @endsection

  @push('scripts')
    <script>
tinymce.init({
selector: '.dynamic-editor'
});

$("#mobile").intlTelInput({
    nationalMode: true,
    // initialCountry: "India",
});

var input = document.querySelector("#mobile"),
  errorMsg = document.querySelector("#error-msg"),
  validMsg = document.querySelector("#valid-msg");

// here, the index maps to the error code returned from getValidationError - see readme
var errorMap = ["Invalid number", "Invalid country code", "Too short", "Too long", "Invalid number"];

// initialise plugin
var iti = window.intlTelInput(input, {
  utilsScript: "{{ asset('tel/js/utils.js') }}"
});

var reset = function() {
  input.classList.remove("error");
  errorMsg.innerHTML = "";
  errorMsg.classList.add("hide");
  validMsg.classList.add("hide");
};

// on blur: validate
input.addEventListener('blur', function() {
  reset();
  if (input.value.trim()) {
    if (iti.isValidNumber()) {
      validMsg.classList.remove("hide");
      return true;
    } else {
      input.classList.add("error");
      var errorCode = iti.getValidationError();
      errorMsg.innerHTML = errorMap[errorCode];
      errorMsg.classList.remove("hide");
      return false;
    }
  }
});

// on keyup / change flag: reset
input.addEventListener('change', reset);
input.addEventListener('keyup', reset);


var input = document.querySelector("#mobile");
window.intlTelInput(input, {
  hiddenInput: "full_phone",
  utilsScript: "{{ asset('tel/js/utils.js') }}" // just for formatting/placeholders etc
});

$('#birth').datepicker({
    format: 'dd-mm-yyyy',
});

jQuery.validator.addMethod("lettersonly", function(value, element) {
  return this.optional(element) || /^[a-z]+$/i.test(value);
}, "Letters only please"); 

$('#form-data').validate({
    errorElement: "span",
    rules: {
        employee_name: {
          required: true,
          lettersonly: true,
        },
        email_id: {
            required: true,
            email: true,
        },
        feature_image: {
            extension: "jpg|png|jpeg",
        },
        employee_id: {
            required: true,
            minlength: 5,
            maxlength: 5,
        },
    },
    messages: {
      required: "This field is required",
      lettersonly: "Only alphabetic characters is valid",
      email: "Please enter a valid email address",
      extension: "Your image must be in valid format",
    },
    submitHandler: function(form) {
    // do other things for a valid form
    form.submit();
    }
});

function deleteGalleryByUrl(url, type, elem) {
    var req_data = {_token: $('meta[name="csrf-token"]').attr('content')};
    $.ajax({
        url: url,
        type: type,
        data: req_data,
        success: function (response) {
            $(elem).parents(".img-rem").remove();
        }
    });
}


function updateGalleryByUrl(url, type, elem) {
    var img_data = $(elem).parents('.position').find('input[name="img-position"]').val();
    var req_data = {'img_position': img_data, _token: $('meta[name="csrf-token"]').attr('content')};
    console.log(req_data);
    $.ajax({
        url: url,
        type: type,
        data: req_data,
        success: function (response) {
            alert('Position Updated');
//                                            $(elem).parents(".img-rem").remove();
            // swal(response);
            swal("Poof! Your imaginary file has been updated!", {
                title: "Position Updated",
                icon: "success"
            });
        }
    });
}


function deleteBTSByUrl(url, type, elem) {
    var req_data = {_token: $('meta[name="csrf-token"]').attr('content')};
    $.ajax({
        url: url,
        type: type,
        data: req_data,
        success: function (response) {
            $(elem).parents(".img-rem").remove();
        }
    });
}


function updateBTSByUrl(url, type, elem) {
    var img_data = $(elem).parents('.position').find('input[name="img-position"]').val();
    var req_data = {'img_position': img_data, _token: $('meta[name="csrf-token"]').attr('content')};
    console.log(req_data);
    $.ajax({
        url: url,
        type: type,
        data: req_data,
        success: function (response) {
            alert('Position Updated');
//                                            $(elem).parents(".img-rem").remove();
            // swal(response);
            swal("Poof! Your imaginary file has been updated!", {
                title: "Position Updated",
                icon: "success"
            });
        }
    });
}

</script>
@endpush

resources/views/backend/employee/index.blade.php
@extends('layouts.app')

@section('contentheader_title')
    EMPLOYEES
@endsection

@section('contentheader_action')
    <a href="{{ route('backend.employee.create') }}" class="btn btn-primary btn-sm">
        <i class="fa fa-plus"></i>
    </a>
@endsection

@section('content')


     <table id="admin-table" class="table table-striped table-bordered table-hover admin-table" style="width:100%">
           <thead class="dark">
            <tr>
                <th>Profile Pic</th>
                <th>Employee ID</th>
                <th>Employee Name</th>
                <th>Mobile</th>
                <th>Email</th>
                <th>Date of Birth</th>
                <th>Action</th>
            </tr>
            </thead>

            <tbody>
            @foreach($datas as $data)
                <tr>
                    <td>
                    <img src="{{asset(Config::get('constants.image_dir').'/'.$data->photo)}}" style="width:50px;"></br>
                    </td>
                    <td>{{ $data->unique_id }}</td>
                    <td>{{ $data->name }}</td>
                    <td>{{ $data->mobile }}</td>
                    <td>{{ $data->email }}</td>
                    <td>{{ $data->birth }}</td>
                    <td>
                    <a href="{{ route('backend.employee.edit', ['id' => $data->id]) }}" class="btn btn-success btn-xs">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <!-- <mv-delete url="{{ route('backend.employee.destroy', ['id' => $data->id]) }}" method="delete"></mv-delete> -->
                    <form action="{{ route('backend.employee.destroy', ['id' => $data->id]) }}" method="post" enctype="multipart/form-data" style="display: inline-block;">
                        @csrf
                    <input type="hidden" name="_method" value="DELETE"> 
                    <button type="submit" class="btn btn-danger btn-xs" data-toggle="confirmation">
                    <i class="fa fa-trash"></i>
                    </button>
                    </form>
                  </td>
                </tr>
            @endforeach
            </tbody>

        </table>

@endsection

@push('scripts')

<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.min.js"></script>
<script>
    $(document).ready(function() {
    $(".admin-table").DataTable({
            "order": [[0, "desc"]],
            "scrollX": true,
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
            "dom": 'Bfrtip',
            "buttons": [
                'excel', 'pdf', 'print'
            ]
        });

    $('[data-toggle=confirmation]').confirmation({
            rootSelector: '[data-toggle=confirmation]',
            placement: 'left',
            onConfirm: function (event, element) {
                element.closest('form').submit();
            }
        });   
});
</script>
@endpush