routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::namespace('Frontend')->name('frontend.')->group(function () {

     // Route::get('/', 'FrontendController@index')->name('home1');
     // Route::get('/hotshot-originals', 'FrontendController@originalsListing')->name('hotshot-originals');
     // Route::get('/hotshot-x', 'FrontendController@XListing')->name('hotshot-x');
     // Route::get('/hotshot-videos', 'FrontendController@videosListing')->name('hotshot-videos');
     // Route::get('/movie/{slug}', 'FrontendController@movie')->name('movie');
     // Route::get('/gallery', 'FrontendController@gallery')->name('gallery');
     // Route::post('/gallery-form-submit', 'FrontendController@galleryPost')->name('gallery-form-submit');
     // Route::view('/terms-of-use', 'frontend.pages.terms')->name('terms-of-use');
     // Route::view('/privacy-policy', 'frontend.pages.policy')->name('privacy-policy');
     // Route::view('/contest-rules', 'frontend.pages.contest-rules')->name('contest-rules');
});

/*
|--------------------------------------------------------------------------
| Register the typical authentication routes for an application.
| Replacing: Auth::routes();
|--------------------------------------------------------------------------
*/

Route::namespace('Auth')->prefix(config('constants.backend_url_prefix'))->group(function () {
    // Authentication Routes...
    $this->get('login', 'LoginController@showLoginForm')->name('login');
    $this->post('login', 'LoginController@login');
    $this->post('logout', 'LoginController@logout')->name('logout');
    // Registration Routes...
    if (config('constants.register')) {
        $this->get('register', 'RegisterController@showRegistrationForm')->name('register');
        $this->post('register', 'RegisterController@register');
    }
    // Password Reset Routes...
    $this->get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    $this->post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    $this->get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('password/reset', 'ResetPasswordController@reset');
});

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
*/

Route::namespace('Backend')->prefix(config('constants.backend_url_prefix'))->name('backend.')->middleware(['auth'])->group(function () {

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::resource('users', 'UserController');
    Route::resource('team', 'TeamController');
    Route::resource('movie', 'MovieController');
    Route::resource('cast', 'CastController');
    Route::resource('video', 'HotVideosController');
    Route::resource('banners', 'BannersController');
    Route::resource('gallery-form', 'GalleryController');
    Route::resource('employee', 'EmployeeController');

    Route::get('movie/deletepic/{id}','MovieController@deletepic');

    Route::post('/movie-gallery-delete/{id}', 'MovieController@deleteGalleryImage')->name('movie-gallery-delete');

    Route::post('/movie-gallery-update/{id}', 'MovieController@updateGalleryImage')->name('movie-gallery-update');

    Route::post('/movie-bts-delete/{id}', 'MovieController@deleteBTSImage')->name('movie-bts-delete');

    Route::post('/movie-bts-update/{id}', 'MovieController@updateBTSImage')->name('movie-bts-update');
});

resources/views/layouts/_partials/contentheader.blade.php
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title">
            @yield('contentheader_title', '')
        </h3>
        <div class="box-tools pull-right">
            @yield('contentheader_action', '')
        </div>
    </div>
</div>

resources/views/layouts/_partials/footer.blade.php
<!-- /.content-wrapper -->
{{-- <footer class="main-footer">
    <strong>Copyright 2017 - {{ \Carbon\Carbon::now()->format('Y') }}
        <a href="{{ config('constants.app.developers.url') }}"
           target="_blank"> {{ config('constants.app.developers.name') }} </a>
    </strong> All right reserved.
</footer> --}}

resources/views/layouts/_partials/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ config('constants.app.url') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">
            <i class="fa fa-user"></i>
        </span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">
            {{ config('app.name') }} <i class="fa fa-user"></i>
        </span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ config('constants.app.logo.profile') }}" class="user-image" alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ config('constants.app.logo.profile') }}" class="img-circle"
                                 alt="User Image">

                            <p>
                                {{ Auth::user()->email }}
                                <small>{{ Auth::user()->created_at }}</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();"
                                   class="btn btn-default btn-flat">Sign out</a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    {{ csrf_field() }}
                                    <input type="submit" value="logout" style="display: none;">
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/_partials/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">

        <ul class="sidebar-menu" data-widget="tree">

            <li class="{{ mv_activate_menu(route('backend.dashboard')) }}">
                <a href="{{ route('backend.dashboard') }}">
                    <i class="fa fa-tachometer"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <li class="{{ mv_activate_menu(route('backend.employee.index')) }}">
                <a href="{{ route('backend.employee.index') }}">
                    <i class="fa fa-tachometer"></i>
                    <span>Employees</span>
                </a>
            </li>

        </ul>

    </section>
</aside>

resources/views/layouts/_partials/social.blade.php
<div class="social-auth-links text-center">
    <p>- OR -</p>
    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
    <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
</div>

resources/views/layouts/_partials/top-message.blade.php
@if ($errors->any())
    <mv-alert message="{!! implode("<br>", $errors->all()); !!}" type="danger"></mv-alert>
@endif

@if(session()->has('message'))
    <mv-alert message="{{ session('message') }}"
              type="{{ session()->has('message_type') ? session('message_type') : 'success' }}"></mv-alert>
@endif